FROM node:22-bookworm-slim AS base

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates curl git openssh-client \
  && mkdir -p /etc/apt/keyrings \
  && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    -o /etc/apt/keyrings/githubcli-archive-keyring.gpg \
  && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
    > /etc/apt/sources.list.d/github-cli.list \
  && apt-get update \
  && apt-get install -y --no-install-recommends gh \
  && rm -rf /var/lib/apt/lists/*

# Keep npm aligned with the lockfile generated by current npm.
RUN npm install -g npm@11.5.1

FROM base AS build

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM base AS runtime

ENV NODE_ENV=production
ENV HOME=/home/node
ENV LUNA_CONFIG_ROOT=/app/config
ENV LUNA_AUTH_ROOT=/app/.luna/auth
ENV GH_CONFIG_DIR=/app/.luna/auth/gh
ENV GH_PROMPT_DISABLED=1
ENV GIT_CONFIG_GLOBAL=/app/.luna/auth/git/config

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY --from=build /app/dist ./dist
COPY --from=build /app/agents ./agents
COPY --from=build /app/config ./config
COPY --from=build /app/skills ./skills
COPY --from=build /app/workflows ./workflows

RUN mkdir -p /app/.runs /app/.luna/auth/git /home/node \
  && ln -sfn /app/.luna/auth/ssh /home/node/.ssh \
  && chown -R node:node /app /home/node

USER node

EXPOSE 4012

CMD ["node", "dist/src/cli.js", "webhook-server", "--host", "0.0.0.0"]
