import { describe, expect, it, vi } from "vitest";
import { createImageGenerateBuiltIn } from "../../../src/capabilities/image-generation/built-ins.js";
import type { ImageGenerationProviderPort } from "../../../src/capabilities/image-generation/contracts.js";
import { unwrapNodeOutputWithBinaryAssets } from "../../../src/core/runtime/artifacts/binary-asset.js";

const state = {
  invocation: {},
  run: { run_id: "run-1" },
  workflow: { id: "social-post", mode: "read_only" },
  steps: {}
};

describe("image-generation capability", () => {
  it("persists generated bytes and returns only an opaque asset reference", async () => {
    const controller = new AbortController();
    const imageBase64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";
    const provider: ImageGenerationProviderPort = {
      provider_id: "pi-imagegen",
      generateImage: vi.fn(async (input) => ({
        operation_id: "image-generation.generate" as const,
        provider: "pi-imagegen" as const,
        provider_id: "pi-imagegen" as const,
        model: "gpt-image-2",
        prompt: input.prompt,
        size: input.size,
        quality: input.quality,
        media_type: "image/png" as const,
        image_base64: imageBase64,
        metadata: {
          provider: "pi-imagegen" as const,
          model: "gpt-image-2",
          prompt: input.prompt,
          size: input.size,
          quality: input.quality,
          media_type: "image/png" as const
        }
      }))
    };
    const artifacts = {
      publish: vi.fn(async (input) => ({
        id: input.path,
        uri: `artifact://run-1/${input.path}`,
        node_id: input.node_id,
        media_type: "image/png"
      })),
      read: vi.fn(async () => new Uint8Array())
    };
    const builtIn = createImageGenerateBuiltIn({
      projectRoot: "/trusted/repo",
      providers: { get: () => provider },
      artifacts
    });

    const executionResult = await builtIn.run({
      state,
      signal: controller.signal,
      node: { id: "image", capability_id: "image-generation.generate" },
      input: {
        provider_id: "pi-imagegen",
        prompt: "A lunar landscape",
        size: "1024x1024",
        quality: "medium"
      }
    });
    const { output: result, binary_assets: binaryAssets } =
      unwrapNodeOutputWithBinaryAssets(executionResult);

    expect(result).toMatchObject({
      provider: "pi-imagegen",
      metadata: { provider: "pi-imagegen" },
      asset: {
        node_id: "image",
        media_type: "image/png"
      }
    });
    expect(result).not.toHaveProperty("image_base64");
    expect(result).not.toHaveProperty("metadata.generator");
    expect(JSON.stringify(result)).not.toContain(imageBase64);
    expect(binaryAssets).toMatchObject({
      produced: [{ node_id: "image" }],
      forwarded: []
    });
    expect(artifacts.publish).toHaveBeenCalledWith(expect.objectContaining({
      node_id: "image",
      format: "png",
      value: imageBase64
    }));

    expect(provider.generateImage).toHaveBeenCalledWith(
      expect.objectContaining({
        operation_id: "image-generation.generate",
        project_root: "/trusted/repo",
        prompt: "A lunar landscape"
      }),
      expect.objectContaining({
        timeoutMs: 180_000,
        maxImageBytes: 25 * 1024 * 1024,
        signal: controller.signal
      })
    );
  });

  it("rejects a provider payload that leaks an internal extension provider", async () => {
    const imageBase64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";
    const provider = {
      provider_id: "pi-imagegen" as const,
      generateImage: vi.fn(async () => ({
        operation_id: "image-generation.generate" as const,
        provider: "openai-codex",
        provider_id: "pi-imagegen" as const,
        model: "gpt-image-2",
        prompt: "A lunar landscape",
        size: "1024x1024" as const,
        quality: "medium" as const,
        media_type: "image/png" as const,
        image_base64: imageBase64,
        metadata: {
          provider: "pi-imagegen" as const,
          model: "gpt-image-2",
          prompt: "A lunar landscape",
          size: "1024x1024" as const,
          quality: "medium" as const,
          media_type: "image/png" as const
        }
      }))
    };
    const builtIn = createImageGenerateBuiltIn({
      projectRoot: "/trusted/repo",
      providers: { get: () => provider as unknown as ImageGenerationProviderPort },
      artifacts: {
        publish: vi.fn(),
        read: vi.fn(async () => new Uint8Array())
      }
    });

    await expect(builtIn.run({
      state,
      node: { id: "image", capability_id: "image-generation.generate" },
      input: {
        provider_id: "pi-imagegen",
        prompt: "A lunar landscape",
        size: "1024x1024",
        quality: "medium"
      }
    })).rejects.toMatchObject({ code: "image_generation_invalid_output" });
  });

});
